# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-FileCopyrightText: Copyright (c) 2026 Xiaomi Corp.
# SPDX-License-Identifier: Apache-2.0
"""Stable frontend tables mirrored from the pinned OmniVoice implementation."""

from __future__ import annotations

import csv
from pathlib import Path

NONVERBAL_TAGS = (
    "laughter",
    "sigh",
    "confirmation-en",
    "question-en",
    "question-ah",
    "question-oh",
    "question-ei",
    "question-yi",
    "surprise-ah",
    "surprise-oh",
    "surprise-wa",
    "surprise-yo",
    "dissatisfaction-hnn",
)

INSTRUCTION_CATEGORIES = (
    ("male", "female", "男", "女"),
    (
        "child",
        "teenager",
        "young adult",
        "middle-aged",
        "elderly",
        "儿童",
        "少年",
        "青年",
        "中年",
        "老年",
    ),
    (
        "very low pitch",
        "low pitch",
        "moderate pitch",
        "high pitch",
        "very high pitch",
        "极低音调",
        "低音调",
        "中音调",
        "高音调",
        "极高音调",
    ),
    ("whisper", "耳语"),
    (
        "american accent",
        "british accent",
        "australian accent",
        "chinese accent",
        "canadian accent",
        "indian accent",
        "korean accent",
        "portuguese accent",
        "russian accent",
        "japanese accent",
    ),
    (
        "河南话",
        "陕西话",
        "四川话",
        "贵州话",
        "云南话",
        "桂林话",
        "济南话",
        "石家庄话",
        "甘肃话",
        "宁夏话",
        "青岛话",
        "东北话",
    ),
)

INSTRUCTION_EN_TO_ZH = (
    "male=男",
    "female=女",
    "child=儿童",
    "teenager=少年",
    "young adult=青年",
    "middle-aged=中年",
    "elderly=老年",
    "very low pitch=极低音调",
    "low pitch=低音调",
    "moderate pitch=中音调",
    "high pitch=高音调",
    "very high pitch=极高音调",
    "whisper=耳语",
)

DURATION_WEIGHTS = (
    "cjk=3.0",
    "hangul=2.5",
    "kana=2.2",
    "ethiopic=3.0",
    "yi=3.0",
    "indic=1.8",
    "thai_lao=1.5",
    "khmer_myanmar=1.8",
    "arabic=1.5",
    "hebrew=1.5",
    "latin=1.0",
    "cyrillic=1.0",
    "greek=1.0",
    "armenian=1.0",
    "georgian=1.0",
    "punctuation=0.5",
    "space=0.2",
    "digit=3.5",
    "mark=0.0",
    "default=1.0",
)

# Inclusive upper bound and weight-table key, in the order used by bisect_left.
DURATION_RANGES = (
    (0x02AF, "latin"),
    (0x03FF, "greek"),
    (0x052F, "cyrillic"),
    (0x058F, "armenian"),
    (0x05FF, "hebrew"),
    (0x077F, "arabic"),
    (0x089F, "arabic"),
    (0x08FF, "arabic"),
    (0x097F, "indic"),
    (0x09FF, "indic"),
    (0x0A7F, "indic"),
    (0x0AFF, "indic"),
    (0x0B7F, "indic"),
    (0x0BFF, "indic"),
    (0x0C7F, "indic"),
    (0x0CFF, "indic"),
    (0x0D7F, "indic"),
    (0x0DFF, "indic"),
    (0x0EFF, "thai_lao"),
    (0x0FFF, "indic"),
    (0x109F, "khmer_myanmar"),
    (0x10FF, "georgian"),
    (0x11FF, "hangul"),
    (0x137F, "ethiopic"),
    (0x139F, "ethiopic"),
    (0x13FF, "default"),
    (0x167F, "default"),
    (0x169F, "default"),
    (0x16FF, "default"),
    (0x171F, "default"),
    (0x173F, "default"),
    (0x175F, "default"),
    (0x177F, "default"),
    (0x17FF, "khmer_myanmar"),
    (0x18AF, "default"),
    (0x18FF, "default"),
    (0x194F, "indic"),
    (0x19DF, "indic"),
    (0x19FF, "khmer_myanmar"),
    (0x1A1F, "indic"),
    (0x1AAF, "indic"),
    (0x1B7F, "indic"),
    (0x1BBF, "indic"),
    (0x1BFF, "indic"),
    (0x1C4F, "indic"),
    (0x1C7F, "indic"),
    (0x1C8F, "cyrillic"),
    (0x1CBF, "georgian"),
    (0x1CCF, "indic"),
    (0x1CFF, "indic"),
    (0x1D7F, "latin"),
    (0x1DBF, "latin"),
    (0x1DFF, "default"),
    (0x1EFF, "latin"),
    (0x309F, "kana"),
    (0x30FF, "kana"),
    (0x312F, "cjk"),
    (0x318F, "hangul"),
    (0x9FFF, "cjk"),
    (0xA4CF, "yi"),
    (0xA4FF, "default"),
    (0xA63F, "default"),
    (0xA69F, "cyrillic"),
    (0xA6FF, "default"),
    (0xA7FF, "latin"),
    (0xA82F, "indic"),
    (0xA87F, "default"),
    (0xA8DF, "indic"),
    (0xA8FF, "indic"),
    (0xA92F, "indic"),
    (0xA95F, "indic"),
    (0xA97F, "hangul"),
    (0xA9DF, "indic"),
    (0xA9FF, "khmer_myanmar"),
    (0xAA5F, "indic"),
    (0xAA7F, "khmer_myanmar"),
    (0xAADF, "indic"),
    (0xAAFF, "indic"),
    (0xAB2F, "ethiopic"),
    (0xAB6F, "latin"),
    (0xABBF, "default"),
    (0xABFF, "indic"),
    (0xD7AF, "hangul"),
    (0xFAFF, "cjk"),
    (0xFDFF, "arabic"),
    (0xFE6F, "default"),
    (0xFEFF, "arabic"),
    (0xFFEF, "latin"),
)


def language_tables() -> tuple[list[str], list[str]]:
    """Return the model language IDs and canonical display names."""
    path = Path(__file__).with_name("omnivoice_languages.tsv")
    with path.open("r", encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream, delimiter="\t"))
    ids = [row["language_id"] for row in rows]
    names = [row["language_name"] for row in rows]
    if len(ids) != 646 or len(set(ids)) != len(ids) or len(set(names)) != len(names):
        raise RuntimeError("packaged OmniVoice language table is malformed")
    return ids, names
